/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "FeederPin3_aliases.h"
#include "FeederPin3.h"
#include "FeederPin2_aliases.h"
#include "FeederPin2.h"
#include "FeederPin1_aliases.h"
#include "FeederPin1.h"
#include "FeederPin4_aliases.h"
#include "FeederPin4.h"
#include "StepperMotorTimer.h"
#include "StepperMotorTimerInterrupt.h"
#include "PWM.h"
#include "PWMClock.h"
#include "Servomotor_aliases.h"
#include "Servomotor.h"
#include "SW1_aliases.h"
#include "SW1.h"
#include "SW2_aliases.h"
#include "SW2.h"
#include "SW3_aliases.h"
#include "SW3.h"
#include "SW4_aliases.h"
#include "SW4.h"
#include "CutterPin1_aliases.h"
#include "CutterPin1.h"
#include "CutterPin2_aliases.h"
#include "CutterPin2.h"
#include "CutterPin3_aliases.h"
#include "CutterPin3.h"
#include "CutterPin4_aliases.h"
#include "CutterPin4.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

